spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subastas_db
    username: postgres
    password: tu_password_local
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Propiedades custom para los tokens lógicos del Backend
jwt:
  secret-key: ${JWT_SECRET_KEY:claveSecretaSuperSeguraParaLaUtnFrvmProgramacionCuatro2026}
  access-expiration: 900000    # 15 minutos (en milisegundos)
  refresh-expiration: 604800000 # 7 días (en milisegundos)